[lb toup] soc: lpc: Fix IOCON_PIO_MODE macros for LPC55xx
Prevents implicit-function-declaration warnings, such as:

> error: implicit declaration of function 'IOCON_PIO_MODE'
> error: implicit declaration of function 'IOCON_PIO_SLEW'
> error: implicit declaration of function 'IOCON_PIO_INVERT'
> error: implicit declaration of function 'IOCON_PIO_DIGIMODE'
> error: implicit declaration of function 'IOCON_PIO_OD'
> error: implicit declaration of function 'IOCON_PIO_ASW';
> error: implicit declaration of function 'IOCON_PIO_I2CFILTER'

(cherry picked from commit 877582413740660f44d5d1a17118004c8076317a)