[lb toup] soc: lpc: Fix IOCON_PIO_MODE macros for LPC55xx
Prevets implicit-function-declaration warnings, such as:

> error: implicit declaration of function 'IOCON_PIO_MODE'
> error: implicit declaration of function 'IOCON_PIO_SLEW'
> error: implicit declaration of function 'IOCON_PIO_INVERT'
> error: implicit declaration of function 'IOCON_PIO_DIGIMODE'
> error: implicit declaration of function 'IOCON_PIO_OD'
> error: implicit declaration of function 'IOCON_PIO_ASW';
> error: implicit declaration of function 'IOCON_PIO_I2CFILTER'

(cherry picked from commit 3a92c9e9800ce123060908b6a67946a9abe439d7)